# Use postgres/example user/password credentials
version: "3.8"

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env.database
    # ports:
    #   - 5432:5432
    networks:
      - stack

  calcom:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .env:/calcom/.env
      - .env.appStore:/calcom/.env.appStore
    ports:
      - 3000:3000
    networks:
      - stack
    depends_on:
      - database
